import { GridRowsProp, GridColDef } from "@mui/x-data-grid";

export const rows: GridRowsProp = [
  {
    id: 1,
    LOCATION_ID: "101",
    LOCATION_TYPE_NM: "Office",
    INTERNAL_EXTERNAL_IND: "Internal",
    LOCATION_DSC: "Headquarters",
    LOCATION_SITE_CD: "HQ01",
    LOCATION_CAMPUS_CD: "Main",
    VENDOR_ID: "VEN001",
    VENDOR_NM: "ABC Corp",
    VENDOR_SHORT_NM: "ABC",
    CITY_NM: "New York",
    COUNTRY_CD: "US",
    COUNTRY_SUBDIVISION_CD: "NY",
    POSTAL_CD: "10001",
    SOURCE_SYSTEM_NM: "SystemA",
    CREATE_AGENT_ID: "user123",
    CREATE_DTM: "2023-12-01T09:00:00Z",
    CHANGE_AGENT_ID: "admin456",
    CHANGE_DTM: "2023-12-05T11:30:00Z",
    EFFECTIVE_START_DTM: "2023-12-01T00:00:00Z",
  },
  {
    id: 2,
    LOCATION_ID: "102",
    LOCATION_TYPE_NM: "Warehouse",
    INTERNAL_EXTERNAL_IND: "External",
    LOCATION_DSC: "Secondary Warehouse",
    LOCATION_SITE_CD: "WH02",
    LOCATION_CAMPUS_CD: "Secondary",
    VENDOR_ID: "VEN002",
    VENDOR_NM: "XYZ Corp",
    VENDOR_SHORT_NM: "XYZ",
    CITY_NM: "Los Angeles",
    COUNTRY_CD: "US",
    COUNTRY_SUBDIVISION_CD: "CA",
    POSTAL_CD: "90001",
    SOURCE_SYSTEM_NM: "SystemB",
    CREATE_AGENT_ID: "user456",
    CREATE_DTM: "2023-12-03T08:00:00Z",
    CHANGE_AGENT_ID: "admin789",
    CHANGE_DTM: "2023-12-07T10:45:00Z",
    EFFECTIVE_START_DTM: "2023-12-03T00:00:00Z",
  },
  {
    id: 3,
    LOCATION_ID: "103",
    LOCATION_TYPE_NM: "Store",
    INTERNAL_EXTERNAL_IND: "Internal",
    LOCATION_DSC: "Downtown Store",
    LOCATION_SITE_CD: "ST03",
    LOCATION_CAMPUS_CD: "Main",
    VENDOR_ID: "VEN003",
    VENDOR_NM: "XYZ Retail",
    VENDOR_SHORT_NM: "XYZR",
    CITY_NM: "San Francisco",
    COUNTRY_CD: "US",
    COUNTRY_SUBDIVISION_CD: "CA",
    POSTAL_CD: "94102",
    SOURCE_SYSTEM_NM: "SystemC",
    CREATE_AGENT_ID: "user789",
    CREATE_DTM: "2023-11-28T10:15:00Z",
    CHANGE_AGENT_ID: "admin012",
    CHANGE_DTM: "2023-12-02T14:20:00Z",
    EFFECTIVE_START_DTM: "2023-11-28T00:00:00Z",
  },
  {
    id: 4,
    LOCATION_ID: "104",
    LOCATION_TYPE_NM: "Warehouse",
    INTERNAL_EXTERNAL_IND: "External",
    LOCATION_DSC: "Primary Warehouse",
    LOCATION_SITE_CD: "WH01",
    LOCATION_CAMPUS_CD: "Main",
    VENDOR_ID: "VEN004",
    VENDOR_NM: "LMN Corp",
    VENDOR_SHORT_NM: "LMN",
    CITY_NM: "Chicago",
    COUNTRY_CD: "US",
    COUNTRY_SUBDIVISION_CD: "IL",
    POSTAL_CD: "60601",
    SOURCE_SYSTEM_NM: "SystemD",
    CREATE_AGENT_ID: "user345",
    CREATE_DTM: "2023-11-30T11:30:00Z",
    CHANGE_AGENT_ID: "admin567",
    CHANGE_DTM: "2023-12-04T09:45:00Z",
    EFFECTIVE_START_DTM: "2023-11-30T00:00:00Z",
  },
  {
    id: 5,
    LOCATION_ID: "105",
    LOCATION_TYPE_NM: "Office",
    INTERNAL_EXTERNAL_IND: "Internal",
    LOCATION_DSC: "Regional Office",
    LOCATION_SITE_CD: "OFF04",
    LOCATION_CAMPUS_CD: "Main",
    VENDOR_ID: "VEN005",
    VENDOR_NM: "PQR Corp",
    VENDOR_SHORT_NM: "PQR",
    CITY_NM: "Houston",
    COUNTRY_CD: "US",
    COUNTRY_SUBDIVISION_CD: "TX",
    POSTAL_CD: "77001",
    SOURCE_SYSTEM_NM: "SystemE",
    CREATE_AGENT_ID: "user678",
    CREATE_DTM: "2023-11-25T12:45:00Z",
    CHANGE_AGENT_ID: "admin890",
    CHANGE_DTM: "2023-11-29T16:30:00Z",
    EFFECTIVE_START_DTM: "2023-11-25T00:00:00Z",
  },
  {
    id: 6,
    LOCATION_ID: "106",
    LOCATION_TYPE_NM: "Store",
    INTERNAL_EXTERNAL_IND: "Internal",
    LOCATION_DSC: "Mall Store",
    LOCATION_SITE_CD: "ST05",
    LOCATION_CAMPUS_CD: "Mall",
    VENDOR_ID: "VEN006",
    VENDOR_NM: "RST Retail",
    VENDOR_SHORT_NM: "RST",
    CITY_NM: "Miami",
    COUNTRY_CD: "US",
    COUNTRY_SUBDIVISION_CD: "FL",
    POSTAL_CD: "33101",
    SOURCE_SYSTEM_NM: "SystemF",
    CREATE_AGENT_ID: "user123",
    CREATE_DTM: "2023-12-10T09:30:00Z",
    CHANGE_AGENT_ID: "admin456",
    CHANGE_DTM: "2023-12-14T13:20:00Z",
    EFFECTIVE_START_DTM: "2023-12-10T00:00:00Z",
  },
  {
    id: 7,
    LOCATION_ID: "107",
    LOCATION_TYPE_NM: "Warehouse",
    INTERNAL_EXTERNAL_IND: "Internal",
    LOCATION_DSC: "Secondary Warehouse",
    LOCATION_SITE_CD: "WH02",
    LOCATION_CAMPUS_CD: "Secondary",
    VENDOR_ID: "VEN007",
    VENDOR_NM: "MNO Corp",
    VENDOR_SHORT_NM: "MNO",
    CITY_NM: "Seattle",
    COUNTRY_CD: "US",
    COUNTRY_SUBDIVISION_CD: "WA",
    POSTAL_CD: "98101",
    SOURCE_SYSTEM_NM: "SystemG",
    CREATE_AGENT_ID: "user234",
    CREATE_DTM: "2023-12-18T08:15:00Z",
    CHANGE_AGENT_ID: "admin567",
    CHANGE_DTM: "2023-12-22T11:30:00Z",
    EFFECTIVE_START_DTM: "2023-12-18T00:00:00Z",
  },
  {
    id: 8,
    LOCATION_ID: "108",
    LOCATION_TYPE_NM: "Office",
    INTERNAL_EXTERNAL_IND: "Internal",
    LOCATION_DSC: "Regional Office",
    LOCATION_SITE_CD: "OFF05",
    LOCATION_CAMPUS_CD: "Main",
    VENDOR_ID: "VEN008",
    VENDOR_NM: "STU Corp",
    VENDOR_SHORT_NM: "STU",
    CITY_NM: "Boston",
    COUNTRY_CD: "US",
    COUNTRY_SUBDIVISION_CD: "MA",
    POSTAL_CD: "02101",
    SOURCE_SYSTEM_NM: "SystemH",
    CREATE_AGENT_ID: "user789",
    CREATE_DTM: "2023-12-15T10:45:00Z",
    CHANGE_AGENT_ID: "admin012",
    CHANGE_DTM: "2023-12-19T09:20:00Z",
    EFFECTIVE_START_DTM: "2023-12-15T00:00:00Z",
  },
  {
    id: 9,
    LOCATION_ID: "109",
    LOCATION_TYPE_NM: "Store",
    INTERNAL_EXTERNAL_IND: "Internal",
    LOCATION_DSC: "City Center Store",
    LOCATION_SITE_CD: "ST06",
    LOCATION_CAMPUS_CD: "Main",
    VENDOR_ID: "VEN009",
    VENDOR_NM: "UVW Retail",
    VENDOR_SHORT_NM: "UVW",
    CITY_NM: "Atlanta",
    COUNTRY_CD: "US",
    COUNTRY_SUBDIVISION_CD: "GA",
    POSTAL_CD: "30301",
    SOURCE_SYSTEM_NM: "SystemI",
    CREATE_AGENT_ID: "user345",
    CREATE_DTM: "2023-12-20T11:00:00Z",
    CHANGE_AGENT_ID: "admin678",
    CHANGE_DTM: "2023-12-24T13:45:00Z",
    EFFECTIVE_START_DTM: "2023-12-20T00:00:00Z",
  },
  {
    id: 10,
    LOCATION_ID: "110",
    LOCATION_TYPE_NM: "Warehouse",
    INTERNAL_EXTERNAL_IND: "Internal",
    LOCATION_DSC: "Tertiary Warehouse",
    LOCATION_SITE_CD: "WH03",
    LOCATION_CAMPUS_CD: "Secondary",
    VENDOR_ID: "VEN010",
    VENDOR_NM: "OPQ Corp",
    VENDOR_SHORT_NM: "OPQ",
    CITY_NM: "Dallas",
    COUNTRY_CD: "US",
    COUNTRY_SUBDIVISION_CD: "TX",
    POSTAL_CD: "75201",
    SOURCE_SYSTEM_NM: "SystemJ",
    CREATE_AGENT_ID: "user123",
    CREATE_DTM: "2023-12-28T09:30:00Z",
    CHANGE_AGENT_ID: "admin456",
    CHANGE_DTM: "2023-12-30T11:20:00Z",
    EFFECTIVE_START_DTM: "2023-12-28T00:00:00Z",
  },
  {
    id: 11,
    LOCATION_ID: "111",
    LOCATION_TYPE_NM: "Office",
    INTERNAL_EXTERNAL_IND: "Internal",
    LOCATION_DSC: "Branch Office",
    LOCATION_SITE_CD: "OFF06",
    LOCATION_CAMPUS_CD: "Main",
    VENDOR_ID: "VEN011",
    VENDOR_NM: "RST Corp",
    VENDOR_SHORT_NM: "RST",
    CITY_NM: "Phoenix",
    COUNTRY_CD: "US",
    COUNTRY_SUBDIVISION_CD: "AZ",
    POSTAL_CD: "85001",
    SOURCE_SYSTEM_NM: "SystemK",
    CREATE_AGENT_ID: "user678",
    CREATE_DTM: "2023-12-25T10:00:00Z",
    CHANGE_AGENT_ID: "admin890",
    CHANGE_DTM: "2023-12-29T12:40:00Z",
    EFFECTIVE_START_DTM: "2023-12-25T00:00:00Z",
  },
];

export const columns: GridColDef[] = [
  { field: "LOCATION_ID", headerName: "Location ID", width: 150 },
  { field: "LOCATION_TYPE_NM", headerName: "Location Type Name", width: 200 },
  { field: "INTERNAL_EXTERNAL_IND", headerName: "Internal External Indicator", width: 220 },
  { field: "LOCATION_DSC", headerName: "Location Description", width: 200 },
  { field: "LOCATION_SITE_CD", headerName: "Location Site Code", width: 180 },
  { field: "LOCATION_CAMPUS_CD", headerName: "Location Campus Code", width: 200 },
  { field: "VENDOR_ID", headerName: "Vendor ID", width: 150 },
  { field: "VENDOR_NM", headerName: "Vendor Name", width: 180 },
  { field: "VENDOR_SHORT_NM", headerName: "Vendor Short Name", width: 200 },
  { field: "CITY_NM", headerName: "City Name", width: 150 },
  { field: "COUNTRY_CD", headerName: "Country Code", width: 150 },
  { field: "COUNTRY_SUBDIVISION_CD", headerName: "Country Subdivision Code", width: 250 },
  { field: "POSTAL_CD", headerName: "Postal Code", width: 150 },
  { field: "SOURCE_SYSTEM_NM", headerName: "Source System Name", width: 220 },
  { field: "CREATE_AGENT_ID", headerName: "Create Agent ID", width: 170 },
  { field: "CREATE_DTM", headerName: "Create Date Time", width: 180 },
  { field: "CHANGE_AGENT_ID", headerName: "Change Agent ID", width: 180 },
  { field: "CHANGE_DTM", headerName: "Change Date Time", width: 180 },
  { field: "EFFECTIVE_START_DTM", headerName: "Effective Start Date Time", width: 250 },
];
